# Generated by Django 4.0.6 on 2022-07-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('value', models.FloatField(blank=True, default=0)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
